name = "plunk"
version = "2.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Library for interacting with Plunk's API (https://useplunk.com) in Gleam - supports both the Erlang and Javascript targets"
licences = ["MIT"]
repository = { type = "github", user = "aosasona", repo = "plunk.gleam" }
gleam = ">= 1.5.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

internal_modules = ["plunk/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_hackney = ">= 1.3.1 and < 2.0.0"
gleeunit = ">= 1.4.0 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
