name: test
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  test:
    env:
      PLUNK_API_KEY: ${{ secrets.PLUNK_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.0"
          gleam-version: "1.6.3"
          rebar3-version: "3"
      - run: gleam format --check src test
      - name: "Install dependencies"
        run: gleam deps download
      - name: "Run all tests"
        run: gleam test
